name: build-application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v4
        with:
          distribution:    'temurin'
          java-version:    '21'
          server-username: PACKAGES_USERNAME_REF # env variable name for username
          server-password: PACKAGES_TOKEN_REF    # env variable name for GitHub Personal Access To

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          PACKAGES_USERNAME_REF: ${{ secrets.PACKAGES_USERNAME }}
          PACKAGES_TOKEN_REF:    ${{ secrets.PACKAGES_TOKEN }}

      - name: Gather Artifacts
        run: |
          mkdir -p artifacts
          cp -v target/cql-on-omop*.jar artifacts/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: application
          path: artifacts
