name: build-application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Platform Dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get -qq update \
            && DEBIAN_FRONTEND=noninteractive sudo apt-get -qq --assume-yes install \
                 maven openjdk-17-jdk

      - uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Gather Artifacts
        run: |
          mkdir -p artifacts
          cp -v target/cql-on-omop*.jar artifacts/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: application
          path: artifacts
