name: publish-container-image

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v4
        with:
          distribution:    'temurin'
          java-version:    '21'
          server-username: PACKAGES_USERNAME_REF # env variable name for username
          server-password: PACKAGES_TOKEN_REF    # env variable name for GitHub Personal Access To

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          PACKAGES_USERNAME_REF: ${{ secrets.PACKAGES_USERNAME }}
          PACKAGES_TOKEN_REF:    ${{ secrets.PACKAGES_TOKEN }}

      - name: Build the Docker image
        run: docker build -t ghcr.io/umg-minai/cql-on-omop:latest -f Containerfile .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGES_USERNAME }} #${{ github.actor }}
          password: ${{ secrets.PACKAGES_TOKEN }} #${{ secrets.GITHUB_TOKEN }}

      - name: Push the Docker image
        run: docker push ghcr.io/umg-minai/cql-on-omop:latest
